services:
  - postgres:latest

variables:
  POSTGRES_DB: testase
  POSTGRES_USER: ase
  POSTGRES_PASSWORD: "ase"

python_2_7_tests:
  image: python:2.7
  script:
    - pip install numpy scipy matplotlib flask psycopg2-binary
    - pip install pyflakes netCDF4
    # using "install from source" instructions
    - export PATH=$PATH:$CI_PROJECT_DIR/bin
    - echo $PATH
    - export PYTHONPATH=$CI_PROJECT_DIR
    - echo $PYTHONPATH
    # tests
    - python --version
    - ase info
    - ase test

# Test with oldest supported Python,
# oldest supported libraries, and minimal set of other dependencies.
python_3_4_tests:
  image: python:3.4-slim
  script:
    - pip install numpy==1.9 scipy==0.13.3
    - pip install --no-deps .
    - ase test

# Test with newest versions of everything.
# We also test with as many optional dependencies as possible.
python_3_tests:
  image: python:3-slim
  script:
    - pip install pyflakes psycopg2-binary
    - pip install .
    - python --version
    - ase info
    - ase test
    # pyflakes code check (Python 3 version)
    - cd $CI_PROJECT_DIR
    - pyflakes ase doc

conda_tests:
   image: continuumio/anaconda3
   script:
     - apt-get install -yq libgl1-mesa-glx
     - conda install -yq pip wheel numpy scipy pyflakes matplotlib flask
     - pip install .
     - python --version
     - ase test

docs_test:
  image: python:3
  script:
    - pip install .[docs]
    - ase info
    - which sphinx-build
    - cd $CI_PROJECT_DIR/doc
    - sphinx-build -W . build
