services:
  - postgres:latest

variables:
  POSTGRES_DB: testase
  POSTGRES_USER: ase
  POSTGRES_PASSWORD: "ase"

# Test with oldest supported Python,
# oldest supported libraries, and minimal set of other dependencies.
python_3_4_tests:
  image: python:3.4-slim-stretch
  script:
    - apt-get install -yq python3-numpy python3-scipy python3-matplotlib
    - pip install .
    - ase test
