services:
  - postgres:latest

variables:
  POSTGRES_DB: testase
  POSTGRES_USER: ase
  POSTGRES_PASSWORD: "ase"

# Test with oldest supported Python,
# oldest supported libraries, and minimal set of other dependencies.
python_3_4_tests:
  image: python:3.4-slim
  script:
    - pip install numpy==1.11 scipy==0.18
    - pip install matplotlib==2.0.0
    - pip install .
    - ase test
