services:
  - postgres:latest

variables:
  POSTGRES_DB: testase
  POSTGRES_USER: ase
  POSTGRES_PASSWORD: "ase"

# Test with oldest supported Python,
# oldest supported libraries, and minimal set of other dependencies.
python_3_5_tests:
  image: python:3.5-stretch
  script:
    - apt-get update
    - apt-get install -yq python3-numpy
    - apt-get install -yq python3-scipy
    - pip install . --no-deps
    - ase test
